### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by id-he-code** [BigTimerr/Privacy-Preserving-ML#1]
你好，最近在学机器学习隐私保护的相关代码，觉得写的特别好，特别清楚，只是调试时在secret_sharing_vector_onring.py这个模块中缺少一些函数，比如运行pvd_server时需要restore_nparray这个函数，不知道作者能再提供一下嘛，在这谢谢了！

**Comment by BigTimerr** [comment]
我把一些文件中用到numpy的地方全部替换程torch的函数了，我在本地测试没问题，你可以现在在pull一下试试。

**Comment by id-he-code** [comment]
好的，谢谢哈
